Dump Models and dependencies in core.py work
mc2-project/secure-xgboost pull request #25
Opened 2020-03-18 00:55 UTC by octaviansima

2020-03-18 02:05 UTC, podcastinator requested changes
Excellent, thanks! Looks good for the most part! Please fix the following?
1. Left a few review comments in the code: some nits, and a couple of security enhancements.
2. Merge in the latest commits on master from the main repo  into your branch, and make sure your changes still build.
3. Also, add your changes to the demo file that you used for testing?

2020-03-18 05:58 UTC, chester-leung commented on enclave/xgboost.conf
> +NumHeapPages=20000
Can you revert this please?

2020-03-18 21:42 UTC, podcastinator commented
LGTM, thanks! @chester-leung Can you double-check to make sure this won't break the remote-control demo?

2020-03-18 21:43 UTC, podcastinator approved these changes

2020-03-18 22:47 UTC, chester-leung commented
@podcastinator will do. We'll have to wait for ACC access though before we can test anything and know for sure.

2020-03-19 03:28 UTC, chester-leung commented
We'll have to add another RPC call for `get_fscore()` to return the output from the server to the client. We can take care of this in another PR though.

2020-03-19 03:56 UTC, chester-leung commented on enclave/src/c_api/c_api.cc
> +#include "base64.h"
Should this be `#include <dmlc/base64.h>`? I had to change it to that to build the code.

If so could you please move this line to under line 9, `#include <dmlc/thread_local.h>`? Thanks!

2020-03-19 04:05 UTC, chester-leung commented
LGTM thanks!

2020-03-19 04:06 UTC, merged