Cryptographic consensus for multiple clients
mc2-project/secure-xgboost pull request #74
Opened 2020-05-24 19:15 UTC by podcastinator

Highlights:
1. Enclaves verify that each submitted command has been signed by all clients
2. Replay protection for submitted commands
3. Multi-client outputs encrypted using a symmetric key reserved for common outputs

2020-05-25 03:29 UTC, chester-leung requested changes
Thanks! A few general comments:

* In `include/xgboost/c_api.h` the modified functions' headers (i.e. \param) should be changed to match the function signature. We should include the newly added parameters -- I added comments to some but not all places that we should make changes for this. We should either add this in this PR or a different one that makes some documentation fixes, up to you. I think there will be other places that will requires some documentation updates in the code, so it may be better to do this in a different PR.

* Do we need the `python-package/securexgboost/build-python.sh` file?

2020-05-25 03:29 UTC, chester-leung commented on enclave/include/enclave_context.h
> +     *void sync_client_key() {
Let's remove this `sync_client_key()` function? If we don't use it here I don't think we need it -- I also don't use it in my multiclient cluster changes.

2020-05-25 03:29 UTC, chester-leung commented on host/src/c_api/c_api.cc
> +  for (int i = 0; i < NUM_CLIENTS; i++) {
Looks like this block of code
```
for (int i = 0; i < NUM_CLIENTS; i++) {
    signer_lengths[i] = strlen(signers[i]);
  }
```

was added to many functions. Let's create a helper function called `get_signer_lengths` (or something) for it?

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signers list of usernames of signing clients
In this file, let's add `nonce`, `nonce_size`, and `nonce_ctr` to the modified functions' param description.

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param sig_len signature length
Here and below for changed functions: I think the `\param` should be `sig_lengths` instead of `sig_len`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param sig_len signature length
`\param sig_lengths signature length`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param sig_len signature length
\param sig_lengths signature length

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param sig_len signature length
\param sig_lengths signature length

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param sig_len signature length
\param sig_lengths signature length

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user_signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user_signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user_signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user_signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user_signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user_signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user_signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature user signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on include/xgboost/c_api.h
> + * \param signature adding signature
The parameter name should be `signatures` (plural) instead of `signature`

2020-05-25 03:29 UTC, chester-leung commented on python-package/securexgboost/core.py
> +                print(args)
Remove this print statement?

2020-05-25 03:29 UTC, chester-leung commented on python-package/securexgboost/core.py
> +def py2c_sigs(signatures, sig_lengths):
Let's move this function to the top of `core.py` where all the other utils functions are

2020-05-25 03:29 UTC, chester-leung commented on python-package/securexgboost/core.py
> +            raise ValueError("Please set your username with the Set_user function or provide a username as an optional argument")
I think this is deprecated. The user function is now called `securexgboost.init_user()`

2020-05-25 03:29 UTC, chester-leung commented on python-package/securexgboost/core.py
> +            raise ValueError("Please set your user with User.set_user function")
`User.set_user` should be `securexgboost.init_user()`

2020-05-25 03:29 UTC, chester-leung commented on python-package/securexgboost/core.py
>              raise ValueError("Please set your username with the Set_user function or provide a username as an optional argument")
`Set_user` should be `securexgboost.init_user`

2020-05-25 03:29 UTC, chester-leung commented on python-package/securexgboost/core.py
>              raise ValueError("Please set your username with the Set_user function or provide a username as an optional argument")
`Set_user` should be `securexgboost.init_user()`

2020-05-25 03:29 UTC, chester-leung commented on python-package/securexgboost/core.py
> +            raise ValueError("Please set your username with the Set_user function or provide a username as an optional argument")
`Set_user` should be `securexgboost.init_user()`

2020-05-27 07:03 UTC, podcastinator commented on demo/python/multiclient/multiclient-demo.py
> +enclave.get_remote_report_with_pubkey()
Deleted the demo; it won't work with the consensus stuff.

2020-05-27 07:04 UTC, podcastinator commented on demo/python/multiclient/scripts/README.md
> +## Make sure you git clone https://github.com/ARMmbed/mbedtls.git in this folder and run `make` inside the repo before running any script
Seems so, currently. We should change it, perhaps in a separate PR.

2020-05-27 07:04 UTC, podcastinator commented on demo/python/multiclient/scripts/gen-user1-cert.sh
> +mbedtls/programs/x509/cert_write selfsign=0 subject_key=userkeys/private_user_1.pem          \
Moving the scripts folder to the home dir.

2020-05-27 21:20 UTC, chester-leung commented
LGTM. Thanks!

2020-05-27 21:20 UTC, chester-leung approved these changes

2020-05-27 21:21 UTC, merged